trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy Stage
  jobs:
  - deployment: Deploy
    displayName: Deploy Nginx to EKS
    environment:
      name: 'development'
      resourceName: 'default'
      resourceType: Kubernetes
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self  # Get your repository files
            fetchDepth: 1
          - task: Bash@3  
            inputs:
              targetType: 'inline'
              script: |
                echo "Checking if manifest exists:"
                ls -la $(Build.SourcesDirectory)/manifests
          - task: Kubernetes@1
            inputs:
              command: 'apply'
              useConfigurationFile: true
              configuration: '$(Build.SourcesDirectory)/manifests/webapp-hello-v1.yml'
          - task: Kubernetes@1
            inputs:
              command: 'apply'
              useConfigurationFile: true
              configuration: '$(Build.SourcesDirectory)/manifests/webapp-hello-service-v1.yml'
