# Please read the README file before you use this pipeline, this requires create a sectet on kubernetes to connect to the ACR.
# Build and push a docker image to Azure Container Registry, then deploy on a on-prem kubernetes.
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - 'frontend/**'

resources:
- repo: self

variables:
  containerName: 'containerName'
  containerRegistry: 'example.azurecr.io'
  containerTag: '$(Build.BuildId)'
  containerPort: '8000'
  containerHostPort: '8000'
  registryServiceConnection: '************************ID************'
  devEnvironment: 'development'
  devEnvironmentVM: 'server-dev'
  prodEnvironment: 'production'
  prodEnvironmentVM: 'server-prod'
  dockerfilePath: '$(Build.SourcesDirectory)/containerFolder/Dockerfile'
  dockerRegistryServiceConnection: '************************ID************'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(containerName)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(containerTag)
- stage: DeployToDev
  displayName: 'Deploy to development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment:
    displayName: 'Job'
    environment:
      name: $(devEnvironment)
      resourceName: $(devEnvironmentVM)
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: 'Deploy YAML file'
            inputs:
              targetType: 'inline'
              script: |
                echo "Creating file manifests.yaml"
                # Create deployment YAML that mounts the ConfigMap
                cat > $(Build.ArtifactStagingDirectory)/manifests.yaml << EOF
                # Deployment
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: $(containerName)
                spec:
                  replicas: 10
                  selector:
                    matchLabels:
                      app: $(containerName)
                  template:
                    metadata:
                      labels:
                        app: $(containerName)
                    spec:
                      containers:
                      - name: $(containerName)
                        image: $(containerRegistry)/$(containerName):$(containerTag) 
                        imagePullPolicy: IfNotPresent        
                        ports:
                        - containerPort: $(containerPort)
                        resources:
                          requests:
                            memory: "64Mi"
                            cpu: "200m"
                          limits:
                            memory: "128Mi"
                            cpu: "500m"
                      imagePullSecrets:
                      - name: secret-name-of-kubernetes
                ---
                # Service 
                kind: Service
                apiVersion: v1
                metadata:
                  name: $(containerName)-service
                spec:
                  type: NodePort
                  selector:
                    app: $(containerName)
                  ports:
                  - protocol: TCP
                    port: 80
                    targetPort: $(containerPort)
                    nodePort: $(containerHostPort)
                EOF
                cat $(Build.ArtifactStagingDirectory)/manifests.yaml
          - task: Bash@3
            displayName: 'Apply deployment'
            inputs:
              targetType: 'inline'
              script: |
                kubectl get all
                kubectl apply -f $(Build.ArtifactStagingDirectory)/manifests.yaml

          